[package]
name = "cool_lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cool_common = { path = "../cool_common"}
plex = "0.2.5"

[[bin]]
name = "cool_lexer"